### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by exocode**
better description how to use the plugin and it's variables.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
@exocode `PLUGIN_` environment variables should be set from the yaml file, not from secrets. We have documentation for plugin creators. I recommend reading these sections:

http://readme.drone.io/0.5/plugin-parameters/
http://readme.drone.io/0.5/plugin-secrets/

The problem here is not the documentation. The problem is the documented secrets are never actually read by the code, which means they will just be ignored. I believe a PR to resolve this issue should look something like this:

```diff
		cli.StringFlag{
			Name:   "rancher_url",
			Usage:  "Url to your rancher server, including protocol and port",
-			EnvVar: "PLUGIN_RANCHER_URL",
+			EnvVar: "PLUGIN_RANCHER_URL,RANCHER_URL",
		},
		cli.StringFlag{
			Name:   "access_key",
			Usage:  "Rancher api access key",
-			EnvVar: "PLUGIN_ACCESS_KEY",
+			EnvVar: "PLUGIN_ACCESS_KEY,RANCHER_ACCESS_KEY",
		},
```

**Comment by exocode** [comment]
added the suggested ``RANCHER_`` prefixes

**Comment by aslafy-z** [comment]
Please, merge this ;-)

**Comment by aslafy-z** [comment]
Can you please rebuild and push to docker hub? Maybe you can setup hub's automatic build on push :)

**Comment by majest** [comment]
Hi, Yes. Sorry for the delay in response. I will rebuild it today

**Comment by majest** [comment]
Dockerhub updated. It will also now build automatically on merge

**Pull request merged**
